project:
  type: website
  output-dir: docs

website:
  title: "DSAN 5500"
  favicon: favicon.png
  sidebar:
    title: "DSAN 5500"
    contents:
      - text: "<i class='bi bi-house pe-1'></i> Home"
        href: index.qmd
      - text: "Syllabus"
        href: syllabus.qmd
      - text: "Resources"
        href: resources.qmd
      - "---"
      - text: "Week 1: Jan 10"
        href: "w01/index.qmd"
      - text: "Week 2: Jan 22"
        href: "w02/index.qmd"
      - text: "Week 3: Jan 29"
        href: "w03/index.qmd"

format:
  html:
    theme: default
    css: styles.css
    toc: true
    include-in-header:
      text: "<script src='https://code.jquery.com/jquery-3.7.1.slim.min.js'></script><script src='/jjcustom.js'></script>"
