project:
  type: website
  output-dir: docs

website:
  title: "DSAN 5500"
  sidebar:
    title: "DSAN 5500<br><span class='subtitle'>Spring 2024, Georgetown, Prof. Jeff</span><br><span class='subtitle'>Mon, 12:30-3:00pm, Car Barn 204</span>"
    contents:
      - text: "<i class='bi bi-house pe-1'></i> Home"
        href: index.qmd
      - text: "Syllabus"
        href: syllabus.qmd
      - text: "Resources"
        href: resources.qmd

format:
  html:
    theme: default
    css: styles.css
    toc: true



