project:
  type: website
  output-dir: docs

website:
  title: ""
  sidebar:
    title: "DSAN 5500<br>Mon, 12:30-3:00pm, Car Barn 204"
    contents:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



